pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Esto descarga todo el repo, incluyendo la carpeta 'jenkins-release-demo'
                git branch: 'main', url: 'https://github.com/AnthonyJohnFlores/devops.git'
            }
        }

        stage('Build') {
            steps {
                sh 'echo "Compilando aplicación..."'
            }
        }

        stage('Test') {
            steps {
                sh 'echo "Ejecutando pruebas..."'
            }
        }

        stage('Package Release') {
            steps {
                sh 'echo "Generando artefacto release..."'
                
                // CAMBIO CLAVE:
                // Le indicamos la ruta completa: carpeta_principal/carpeta_src
                sh 'zip -r release.zip ./jenkins-release-demo/src'
            }
        }

        stage('Publish Artifact') {
            steps {
                sh 'echo "Publicando artefacto Prueba 3..."'
            }
        }
    }

    post {
        success {
            // El zip se crea en la raíz, así que esto sigue funcionando igual
            archiveArtifacts artifacts: 'release.zip', fingerprint: true
            echo "Release generado exitosamente."
        }
        failure {
            echo "Falló el release."
        }
    }
}