pipeline {
    agent any

    // Definimos variables globales para el pipeline
    environment {
        APP_VERSION = "1.0.${BUILD_NUMBER}" // El número de build de Jenkins
    }

    stages {
        stage('Checkout') {
            steps {
                echo "Descargando versión del repositorio..."
                git branch: 'main', url: 'https://github.com/AnthonyJohnFlores/devops.git'
            }
        }

        stage('Code Analysis') { // Paso simulado
            steps {
                echo "Analizando calidad del código con SonarQube (Simulado)..."
                sleep 2 // Pausa de 2 segundos
                echo "Calidad del código: APROBADA"
            }
        }

        stage('Build') {
            steps {
                echo "Compilando aplicación versión ${APP_VERSION}..."
                // Simulamos que se crea un binario o ejecutable
                sh 'echo "Binario compilado" > ./jenkins-release-demo/src/app.bin'
            }
        }

        stage('Test') {
            steps {
                echo "Ejecutando pruebas unitarias..."
                sleep 2
                echo "Tests: 100% Pasados."
            }
        }

        stage('Package Release') {
            steps {
                echo "Generando paquete release-v${APP_VERSION}.zip..."
                
                // Usamos la variable de entorno para el nombre del archivo
                // Comprimimos el contenido de la carpeta src
                sh "zip -r release-v${APP_VERSION}.zip ./jenkins-release-demo/src"
            }
        }

        stage('Deploy Approval') { // NUEVO:Demo de despliegue a produccion
            steps {
                script {
                    // Esto pausará el pipeline hasta que tú le des clic en la web
                    input message: '¿Deseas desplegar esta versión a Producción?', ok: 'Desplegar'
                }
            }
        }

        stage('Publish Artifact') {
            steps {
                echo "Publicando artefacto release-v${APP_VERSION}.zip a Producción..."
                sleep 2
                echo "¡Despliegue finalizado con éxito!"
            }
        }
    }

    post {
        success {
            // Guardamos el artefacto con el nombre dinámico
            archiveArtifacts artifacts: "release-v${APP_VERSION}.zip", fingerprint: true
            echo "Pipeline finalizado. Artefacto v${APP_VERSION} archivado."
            echo "Este es el examen final."
        }
        failure {
            echo "El pipeline falló. Revisar logs."
        }
    }
}

